@startuml

title __FACTORY's Class Diagram__\n

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.CloudCoverDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        interface org.example.Tomorroio.model.factory.DatasetFactory {
            {abstract} + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.HumidityDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.PressureDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.TemperatureDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.WindGustDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace model {
      namespace factory {
        class org.example.Tomorroio.model.factory.WindSpeedDatasetFactory {
            + createDataset()
        }
      }
    }
  }
  

  org.example.Tomorroio.model.factory.CloudCoverDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory
  org.example.Tomorroio.model.factory.HumidityDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory
  org.example.Tomorroio.model.factory.PressureDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory
  org.example.Tomorroio.model.factory.TemperatureDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory
  org.example.Tomorroio.model.factory.WindGustDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory
  org.example.Tomorroio.model.factory.WindSpeedDatasetFactory .up.|> org.example.Tomorroio.model.factory.DatasetFactory

@enduml
