@startuml

title __CONTROLLER's Class Diagram__\n

  namespace org.example.Tomorroio {
    namespace controller {
      class org.example.Tomorroio.controller.WeatherChartController {
          + WeatherChartController()
          + updateCharts()
      }
    }
  }
  

  namespace org.example.Tomorroio {
    namespace controller {
      interface org.example.Tomorroio.controller.WeatherController {
          {abstract} + updateCharts()
      }
    }
  }
  

  org.example.Tomorroio.controller.WeatherChartController .up.|> org.example.Tomorroio.controller.WeatherController
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.view.WeatherView : chartView
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.CloudCoverDatasetFactory : cloudCoverDatasetFactory
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.HumidityDatasetFactory : humidityDatasetFactory
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.PressureDatasetFactory : pressureDatasetFactory
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.TemperatureDatasetFactory : temperatureDatasetFactory
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.WeatherData : weatherData
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.WindGustDatasetFactory : windGustDatasetFactory
  org.example.Tomorroio.controller.WeatherChartController o-- org.example.Tomorroio.model.factory.WindSpeedDatasetFactory : windSpeedDatasetFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
